### ISSUE TITLE
case mismatch in file names for `perform_full_pearce.py`

### ISSUE THREAD

**Issue by mstimberg** [thomasMisiek/mixed-coordination-models#4]
[Opened as part of the ReScience review: ReScience/submissions#62]

At the end of a `perform_full_pearce.py` run, I get an error
```
FileNotFoundError: [Errno 2] No such file or directory: '../images/results_pearce.jpg'
```
The reason is that a number of files are named `.JPG` instead of `.jpg` (and I'm on Linux with a case-sensitive file system).

**Comment by thomasMisiek** [comment]
Ok its resolved.
