### ISSUE TITLE
`random_grid_search` fails if `results` dir does not exist

### ISSUE THREAD

**Issue by mstimberg** [thomasMisiek/mixed-coordination-models#7]
[Opened as part of the ReScience review: https://github.com/ReScience/submissions/issues/62]

Running e.g. the `Geerts Replication.ipynb` notebook in a freshly cloned repository will fail, since it assumes that the `results` directory exists. Using `os.makedirs` with `exists_ok=True` could simplify things here.

**Comment by thomasMisiek** [comment]
Ok, fixed.
